---
title: "Problem 11"
author: "Schwab"
date: "4/13/2022"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(babynames)
library(mdsr)
```

```{r}
head(Violations)
```

The first part below is incorrect. I'm accidentily double counting all the zip codes in the mutate function 


```{r}
Violations %>%
  group_by(zipcode) %>%
  mutate(number_of_violation=n()) %>% #This line counts the number of violations
  
  filter(
    number_of_violation >49
    ) %>%
  
  summarise(
    median_score=median(score,na.rm=TRUE),
    number_o_inspection=number_of_violation
    ) %>% #I had to strip the median score so that the value would match the favstats(score~zipcode,data=Violations) output. Is the point that we should not do that?
  
  arrange(desc(median_score))  %>%
  distinct() %>%
  ggplot(aes(median_score,number_o_inspection))+
  geom_col()+
  labs(y="Number of inspections by zip code",x="median score")


```

```{r}
Violations %>%
  group_by(zipcode) %>% 
  filter(
    n()>49, 
    boro == "MANHATTAN") %>% #filter the number of violations to be greater than 49
  
  summarise(
    median_score=median(score,na.rm=TRUE),
    number_of_inspections=n()
    ) %>% #I had to strip the median score so that the value would match the favstats(score~zipcode,data=Violations) output. Is the point that we should not do that?
  
  ggplot(aes(median_score,number_of_inspections)) +  #plotting score vs inspection
    geom_point() +
    labs(
      x="Median Score",
      y="Number of Inspections")
  
```