---
title: "Problem 1"
author: "Schwab"
date: "4/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(babynames)

#This makes the Random_subset
Random_subset <- babynames %>%
  filter(year=="2003" & name=="Bilal" & sex =="M" |year=="1999" & name=="Terria" & sex =="F" |year=="2010" & name=="Naziyah" & sex =="F" |year=="1989" & name=="Shawana" & sex =="F" |year=="1989" & name=="Jessi" & sex =="F" |year=="1928" & name=="Tillman" & sex =="M"|year=="1981" & name=="Leslee" & sex =="F" |year=="1981" & name=="Sherise" & sex =="F"|year=="1920" & name=="Marquerite" & sex =="F" |year=="1941" & name=="Lorraine" & sex =="M") 
```

```{r part_a}

Random_subset %>% filter( n>40 & n<85) 
```

```{r part_b}

Random_subset %>% filter(6 == nchar(name))
```

```{r part_c}
Random_subset %>% mutate(total=n/prop) %>% filter(total >1990000 & sex=="F")
```

```{r part_d}
Random_subset %>% 
  group_by(year) %>%
  
  summarise(total=sum(n))
```