---
title: "Problem 2"
author: "Schwab"
date: "4/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(babynames)
```

```{r part_a}
#babynames %>% select(n>100)
#this should be a filter
babynames %>% filter(n>100)
```

```{r part_b}
babynames %>% select(-year)
#There is nothing wrong with this, it is removing the year column
```

```{r part_c}
#babynames %>% mutate(name_length == nchar(name))
#There are two equal signs it should be one. 
babynames %>% mutate(name_length = nchar(name))
```

```{r part_d}
#babynames %>% sex == M %>% select(-prop)
#This is missing a filter and needs quotes it should be 
babynames %>% filter(sex == "M") %>% select(-prop)
```

```{r part_e}
babynames %>% select(year, year, sex) 
#Nothing is wrong with this, but there is an extra year. 
```

```{r part_f}
babynames %>% group_by(n) %>% summarize(ave = mean(n))
#I think this means to group by year and find the average number of children born per name. Maybe its by name
babynames %>% group_by(year) %>% summarize(ave = mean(n))
#Group_by(names) shows the average number of children born that year. 
babynames %>% group_by(name) %>% summarize(ave = mean(n))
```

```{r part_g}
babynames %>% group_by(n > 100) %>% summarize(total = n())
# I don't think this is wrong. Its counting the number of times a name is used more than 100 times in a year for a baby. 
```
