---
title: "More Function Practice"
author: "Schwab"
---

Here are three problems for you to try. Don't overly complicate your functions.

If you already have a some programming experience I encourage you to take a look at the anonymous_function.qmd. In it you will see examples of otherways in which you can write functions in R.

R is a vectorized language, and one thing that means is that you can easily add values from vectors element-wise. You will see what I mean in the problem below

Problem 1.

Make two vectors, each with 5 integers and save them as vector 1 and vector 2. Then make a function that will, add or subtract these vectors.

Problem 2.

The function below is broken. It's syntax (the way it is typed is not great). Your task is to fix it and make the style conform to the style guide. Then when you run the function with default arguments

```{r}
FixMe <- function(argument1 = "fixed", argument2= "broken"){
  
  if(is.character(argument1)){
   print(argument2) 
  }
  
  else_if(argument1 == argument2){
    print("still broken")
  }
  else{
    print(argument1)      
  }



```

Problem 3

Make a function that takes a students name from this class and draws a map of their home country.
