---
title: "SDS 192: Intro to Data Science"
author: "Nicholas Schwab"
date: today

output: html_document

format:
  html:
    toc: true
    toc-depth: 1
    toc-float: true
    toc-location: left
    toc-title: ""
    df-print: kable
    smooth-scroll: true
---

```{=html}
<style>
h1{font-weight: 400;}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 16/2, fig.height = 9/2
)

# tidyverse R packages:
library(ggplot2)
library(dplyr)
library(tibble)
library(tidyr)
library(readr)
library(purrr)
library(forcats)
library(stringr)
library(lubridate)
library(forcats)

# CRAN R packages:
library(knitr)
library(fivethirtyeight)
library(nycflights13)
library(gapminder)
library(babynames)
library(scales)
library(moderndive)

library(maps)
library(mapproj)
library(patchwork)

# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

```{=html}
<style>
h1{font-weight: 400;}
</style>
```
# Schedule

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTG_b6upDZcPxXB92LHYIhV1uAXgeVGaMsZ3sDRPuSQN74JdhkKhZQVjw6T68I3zsP8KGYzDSVTZW64/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false&amp;gid=0&amp;range=A1:D3" width="100%" height="200">

</iframe>

<!-- # Day 26: Final project work. -->

<!-- Just working the final project today.  -->

<!-- # Day 25: More maps with leaflet.  -->

<!-- UMass $10,000 dollar/year scholarship to study Informatics, let me know if you want more info. -->

<!-- -   more maps -->

<!-- -   provider tiles -->

<!-- -   slides  -->

<!-- [Final Project](./course-materials/project-instructions/final-project.html) due Tuesday Dec 20 at midnight. Presentation of project is Wednesday Dec 21 at 10:30am.  -->

<!-- # Day 24: Maps with ggplot2 and leaflet.  -->

<!-- We'll be working from [this site](./course-materials/lectures/maps-ggplot.html) today.  -->

<!-- # Day 23: SQL Project Day  -->

<!-- Time to work on Project 3 -->

<!-- # Day 22: More SQL  -->

<!-- -   Review problems 1,2,3 and 5 from chapter 15 -->

<!-- -   Short Lecture?  -->

<!-- -   [Project 3](./course-materials/project-instructions/project-3/project3.html) -->

<!-- # Day 21: Intro to SQL and dbplyr() -->

<!-- -   [Example](./course-materials/lectures/SQL-example-yelp.html) -->

<!-- -   Try Problems 1,2,3 and 5 from chapter 15 with dbplyr and SQL -->

<!-- -   A [Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/email/other/SQL+for+Data+Science.pdf) and here's [another one](https://intellipaat.com/blog/wp-content/uploads/2022/10/SQL-Commands-Cheat-Sheet-2022.jpg) -->

<!-- # Day 20: Scraping Data -->

<!-- -   Discuss Pivot Practice. -->

<!-- -   [Scraping from website example](./course-materials/lectures/scrape-data.html)  -->

<!-- -   MDSR Chapter 6 Problem 3 and 4 for homework 6 due Monday. -->

<!-- # Day 19: Tidy Data Pivot Practice -->

<!-- [Just Pivot practice with this assignment](https://github.com/MTH190/Pivot_practice) -->

<!-- Clone the assignment by visiting the link above.  -->

<!-- # Day 18: Tidy Data -->

<!-- -   45 minutes on tidy data with [hw-05](https://github.com/MTH190/hw-05) -->

<!-- -   30 minutes on project  -->

<!-- -   No class on Friday Nov 11th or Nov 23rd -->

<!-- # Day 17: Continue working on Project 2 -->

<!-- -   Comment your data with `#` -->

<!-- -   Use pull to save data to avoid retyping.  -->

<!-- -   I'll continue to check slack and github to give feedback. -->

<!-- # Day 16: Project 2 -->

<!-- Github: -->

<!-- -   Together: Push to github HW-03, HW-04, and Project-1. -->

<!-- Remember: -->

<!-- -   **pull** new changes -->

<!-- -   make edits on your computer -->

<!-- -   **commit** your local changes -->

<!--     -   this step may be repeated -->

<!-- -   **pull** again to avoid merge conflicts -->

<!-- -   **push** your commit(s) to GitHub -->

<!-- [FEC Data Lecture](./course-materials/lectures/mdsr-wrangling-fec20.html) -->

<!-- [Project 2](./course-materials/project-instructions/project-2/project-2-fec-20.html) -->

<!-- Project 2 teams: -->

<!-- -   Ajani, Ida, Magdalena -->

<!-- -   James & Kathrine -->

<!-- # Day 15: Work on HW 4. -->

<!-- Questions on HW 4 -->

<!-- Point out the tidyverse [Coding Style Guide](https://style.tidyverse.org/) -->

<!-- -   [Files](https://style.tidyverse.org/files.html) -->

<!-- -   [Syntax](https://style.tidyverse.org/syntax.html) -->

<!-- -   [Pipes](https://style.tidyverse.org/pipes.html) -->

<!-- -   [ggplot2](https://style.tidyverse.org/ggplot2.html) -->

<!-- Practice: Merge Conflicts with github together -->

<!-- In preparation for Project 2: `install.packages("remotes")` `remotes::install_github("baumer-lab/fec20")` -->

<!-- # Day 14: Ok Really Start HW 4 -->

<!-- Discuss Problems 1 and 3 from Chapter 5 -->

<!-- Start work on HW 4 -->

<!-- [Problem 3 solution](./MY-MDSR-SOLUTIONS/Chapter%205%20Problems/Chapter%205%20Problems/Problem-3-new.html) -->

<!-- # Day 13: More Practice -->

<!-- Push HW 3 to Github -->

<!-- Discuss Problems 1 and 3 from Chapter 5 -->

<!-- # Day 12: Joins -->

<!-- ## [The Joins](./course-materials/lectures/mdsr-the-joins.html) -->

<!-- Try [Chapter 5 problems 1, 3 and 4](https://mdsr-book.github.io/mdsr2e/ch-join.html#join-exercises) start in class continue for homework we'll discuss Friday -->

<!-- # Day 11: Project 1 workday and group_by() -->

<!-- ## [group_by() (and rename)](./course-materials/lectures/mdsr-group_by-and-rename.html) -->

<!-- ## Project_time -->

<!-- # Day 10: Project 1 -->

<!-- Discuss exercises 1,2,3,5 and 6 from chapter 4. -->

<!-- ## On Coding -->

<!-- [learning to code](./course-materials/lectures/mdsr-learning-to-code.html) -->

<!-- ## Project 1 -->

<!-- Copy it from github. [Here's the outline](./course-materials/project-instructions/project-1/project-1-hcc-data-outline.html) -->

<!-- # Day 9: The verbs -->

<!-- [The Verbs](./docs/course-materials/lectures/mdsr-the-verbs.html) [The Verbs](./course-materials/lectures/mdsr-the-verbs.html) -->

<!-- Discuss exercises 1,2,3 from chapter 4. -->

<!-- Problem 5 and 6 for Classwork -->

<!-- [Chapter 3: Problem 3 and 7](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#datavizII-exercises) -->

<!-- # Day 8: Class is cancelled but... -->

<!-- ## I expect you to do the reading and try problem 1,2, and 3 from chapter 4. -->

<!-- I made you the dataframe for exercise 4.4 number 1 so you can play with the code. You can copy it from [here.](./course-materials/in-class-activities/chapter-4-problem-1.html) We'll discuss this problem, number 2 and also 3 on Friday. -->

<!-- # Day 7: Discuss Homework -->

<!-- ## Go over interesting bits from the homework: -->

<!-- -   HW2 -->

<!--     -   load(), inline code, nrow()\ -->

<!--     -   question 4 and 5 -->

<!-- -   HW3 -->

<!--     -   brief analysis of code -->

<!--     -   stuck anywhere? -->

<!-- ### Practice: -->

<!-- [Chapter 3: Problem 3 and 7](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#datavizII-exercises) -->

<!-- # Day 6: Color and Grammar of Graphics -->

<!-- ## [Color lecture](./course-materials/lectures/mdsr_color.html) -->

<!-- ## [Grammar of graphics](./course-materials/lectures/mdsr-grammar-of-graphics.html) -->

<!-- ## Activity -->

<!-- -   [We'll do problems 3.1 #1 and 3 in class](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#datavizII-exercises) -->

<!-- # Day 5: Digestion Day -->

<!-- ## Let us talk about these -->

<!-- -   [Chapter 2 Take Aways](https://docs.google.com/document/d/184nd7HdObXgeyuq7TUHYXjThkHWc0O45GDD1BG1m40E/edit?usp=sharing) -->

<!-- -   Discuss [Problems 1 & 6 & 3](https://mdsr-book.github.io/mdsr2e/ch-vizI.html#datavizI-exercises) -->

<!-- -   Discuss [Lab_01](./course-materials/lab-instructions/lab-01/lab-01-plastic-waste.html) -->

<!-- -   Quick check in [HW 02](./course-materials/hw-instructions/hw-02/hw-02-airbnb-edi.html) -->

<!-- ## [Color exercise](./course-materials/in-class-activities/Color_exercises.html) -->

<!-- # Day 4: Using GGplot -->

<!-- ## Activity: [Intro to ggplot2](./course-materials/in-class-activities/Activity-ggplot2.html) -->

<!-- ## [Lab_01](./course-materials/lab-instructions/lab-01/lab-01-plastic-waste.html) -->

<!-- # Day 3: Check in and Taxonomy -->

<!-- ## Updates: -->

<!-- -   Issues with some packages installing on Server: 'coronavirus', 'ggimage', 'dsbox' -->

<!-- -   What times of the day do you do your homework. When would AJ's office hours work for you? -->

<!-- ## Check in on HW 1 -->

<!-- [HW 1 Take Aways](https://docs.google.com/document/d/1jtF58XftxCVLf8DMDsrDLyxKY752puwckm1d6db-CYo/edit?usp=sharing) -->

<!-- HW 1 due by midnight tonight. -->

<!-- ## Taxonomy -->

<!-- [Lecture on Taxonomy](./course-materials/lectures/mdsr_viz_1_taxonomy.html) -->

<!-- [Activity on Taxonomy](./course-materials/in-class-activities/Activity_Taxonomy_of_Graphics.html) -->

<!-- ## Let's look at HW 2 -->

<!-- [HW 02](./course-materials/hw-instructions/hw-02/hw-02-airbnb-edi.html) should be shared with you through github You have to clone the repo and use your token as a password. -->

<!-- ## Get a NYTimes account -->

<!-- [You get this free through HCC](https://www.hcc.edu/library/find-resources/databases-and-journals/nyt-login) -->


# Day 2 Taxonomy



Please complete [this survey](https://smithcollege.qualtrics.com/jfe/form/SV_bmy8BNkIp4SpzXo) for Prof. Cao's study

### For Help

[The six-fixes](https://docs.google.com/document/d/1P7IyZ4On9OlrCOhygFxjC7XhQqyw8OludwChz-uFd_o/edit) [Student hours](/course-materials/syllabus/syllabus.qmd) [Spennlli center](https://www.smith.edu/academics/spinelli-center/tutoring#disciplines)

::: {.callout-tip collapse="true"}
## Screenshots Help

Help us help you: take screenshots of your screen and post them to Slack.

-   macOS: Command+Shift+3 to take shot of whole screen, Command+Shift+4 to take subportion

-   Windows: Shift-Windows Key-S and Snip & Sketch

-   Linux: Print screen

-   Chromebook: Shift + Ctrl + Show windows
:::

[Prologue to 1.4 document](https://docs.google.com/document/d/1EJ389lsPzAutfq1HEspdTNyyVAk8AJDItQPXgI58dus/edit?usp=sharing)

::: {.callout-note collapse="true"}
\##*Announcement-Google*

[Google will be on campus.](https://rsvp.withgoogle.com/events/fall-2023-cap-outreach_3b5b3d/forms/registration)

-   Building a Tech Career, Sept 13 6:30-8:30pm, Campus Center room 103/104

-   Resume Building and the Technical Interview, Sept 14 6-8pm, Campus Center room 103/104

-   Self-Advocacy in Tech, Sept 15 12:15-1:15pm, Campus Center room 204
:::

### Lecture

[Taxonomy of graphs](course-materials/lectures/mdsr_viz_1_taxonomy.qmd)

### Finish Lecture from Day 1

[How R builds a Graph](/course-materials/lectures/How-R-Builds-a-graph.qmd)


<!-- ## Activity -->

<!-- [UNvotes](./course-materials/application-exercises/ae-01a-un-votes/unvotes.html) -->

<!-- or -->

<!-- [COVID-19](./course-materials/application-exercises/ae-01b-covid/covid.html) -->

<!-- ## HW 1 should be shared with you via github. -->

<!-- -   Check your email. -->

<!-- -   I'd like to start this in class so we're on the same page. -->

<!-- -   [Here's a link just in case, but don't click it](./course-materials/hw-instructions/hw-01/hw-01-pet-names.html) -->


# Day 1: No Computer Data Viz

[Syllabus](./course-materials/syllabus/syllabus.html) Log into [Slack](https://sds-192-ns-202401.slack.com) Website tour Bring Computers to Class

### Lecture

[Data Viz No Computers](./course-materials/first-day-survey/Data-Viz-No-Computers.qmd)

### General Questions and Comments

::: {.callout-note collapse="true"}
## Homework:

-   In slack- post about yourself (check your email for a slack invitation). Include somethings you want to tell people and your github username.

-   Sign up for [github here](https://github.com/), if you don't already have an account. We will very carefully link your github account to our github classroom account.

-   Read the prologue to chapter 1.4 of MDSR. [Add some notes to our summary.](https://docs.google.com/document/d/1EJ389lsPzAutfq1HEspdTNyyVAk8AJDItQPXgI58dus/edit?usp=sharing)
:::

### Walk to MCConnell 213 and 214

My office and group study room.
