---
title: "Excersie 3"
author: "Schwab"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mdsr)
library(tidyverse)
library(RMySQL)

con <- dbConnect_scidb("airlines")
flights <- tbl(con, "flights")
carriers <- tbl(con, "carriers")
airports <- tbl(con, "airports")

```

```{sql connection=con}
/*Below is how we can see the tables*/
SHOW TABLES;
```

```{sql connection=con}
/*Below is how we can describe airports to find the countries*/ 
DESCRIBE flights;
```

```{r }
#Here flights is a table that was made in the setup. I'm using the normal dplyr verbs to show the years. How many are going to US
airports %>%
  select(country) %>%
  distinct()
#Haha, they are all domestic flights. Unless I'm misunderstanding the variable 
```

```{r}
#I cannot get the n() function to work here. I'll try in SQL code
flights %>%
  filter(dest == "DFW" & year=="2010" & month =="05" & day == "14") |>
  group_by(year) |>
  summarise(total=n())

  
  
```

```{sql connection=con}
/*Below Here is the same result in SQL as opposed to R. It looks like there were 754 flights into DFW */ 

SELECT 
  count(dest)
FROM 
  flights 
WHERE dest= 'DFW' AND year = 2010 AND month = 5 AND day = 14;



```