---
title: "Excersie 5"
author: "Schwab"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mdsr)
library(tidyverse)
library(RMySQL)

con <- dbConnect_scidb("airlines")
flights <- tbl(con, "flights")
carriers <- tbl(con, "carriers")
airports <- tbl(con, "airports")

```

Problem 5 (Medium): Use the dbConnect_scidb function to connect to the airlines database to answer the following problem. Of all the destinations from Chicago O’Hare (ORD), which were the most common in 2010?

```{sql connection=con}
/*Below is how we can see the tables*/
SHOW TABLES;
```

```{sql connection=con}
/*Below is how we can describe airports to find the countries*/ 
DESCRIBE flights;
```

```{r}
#I cannot get the n() function to work here. I'll try in SQL code
most_common<- flights %>%
  filter(origin == "ORD" & year== 2010 ) |>
  group_by(dest) |>
  summarise(total_flights=n()) |>
  arrange(desc(total_flights))
  
show_query(most_common)
```

```{sql connection=con}
/*Below Here is the same result in SQL as opposed to R. It looks like there were 754 flights into DFW */ 

SELECT `dest`, COUNT(*) AS `total_flights`
FROM `flights`
WHERE (`origin` = 'ORD' AND `year` = 2010.0)
GROUP BY `dest`
ORDER BY `total_flights` DESC;



```