---
title: "Chapter 3.3 Extended Example"
author: ""
date: ""
output: html_document
---

Change the author name to your name and add friday's date. 

Your homework is to recreate [this graph](https://mdsr-book.github.io/mdsr2e/03-datavizII_files/figure-html/joseph-1.png) in [section 3.3](https://mdsr-book.github.io/mdsr2e/ch-vizII.html#sec:babynames) with your name.  Its due Friday at midnight. Don't start this Thursday night, you will be sad. After you finish this assignment knit it, commit it, an push it to git so I can grade it over the weekend. 

I've added a setup chunk and the first chunk from the text. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(mosaicData)
library(knitr)
library(babynames)
BabynamesDist <- make_babynames_dist()
```

```{r filter}

nicholas <- BabynamesDist |> 
  filter(name == "Nicholas" & sex =="M")

name_plot <- ggplot(data = nicholas, aes(x = year))
```

```{r name_plot_bars}
name_plot <- name_plot +
  geom_col(
    aes(y = count_thousands * alive_prob), 
    fill = "#b2d7e9", 
    color = "white",
    size = 0.1
  )

name_plot
```

```{r add-a-bar}
name_plot <- name_plot + 
  geom_line(aes(y = count_thousands), size = 2)

name_plot
```

```{r labels}
name_plot <- name_plot +
  ylab("Number of People (thousands)") + 
  xlab(NULL)
```

```{r summary}
summary(name_plot)
```

```{r making_a_quartile}
wtd_quantile <- Hmisc::wtd.quantile
median_yob <- nicholas %>%
  summarize(
    year = wtd_quantile(year, est_alive_today, probs = 0.5)
  ) %>% 
  pull(year)
median_yob


```
```{r}
name_plot <- name_plot +
  geom_col(
    color = "white", fill = "#008fd5", 
    aes(y = ifelse(year == median_yob, est_alive_today / 1000, 0))
  )
name_plot

```
```{r}
context <- tribble(
  ~year, ~num_people, ~label,
  1935, 40, "Number of Nicholas's \n born each year",
  1915, 13, "Number of Nicholas's \n born each year
  \nestimated to be alive\non 1/1/2014", 
  2003, 40, "The median\nliving Nicholas\n is 30 years old", 
)

name_plot +
  ggtitle("Age Distribution of American Boys Named Joseph") + 
  geom_text(
    data = context, 
    aes(y = num_people, label = label, color = label)
  ) + 
  geom_curve(
    x = 1990, xend = 1990, y = 35, yend = 30, 
    arrow = arrow(length = unit(0.1, "cm")), curvature = 0.2
  ) + 
  scale_color_manual(
    guide = FALSE, 
    values = c("black", "black", "darkgray")
  ) + 
  ylim(0, 42)+
  theme_classic()
```
