---
title: "Problem_4"
author: "Schwab"
date: "5/4/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(mdsr)
library(tidyverse)
library(mosaic)
library(lubridate)
library(purrr)
library(rvest) #I thought this loaded with the tidyverse, but I guess I need to load it separately. 
library(janitor) #I use this to clean up the startrek table with #clean_names.

```



```{r}
#I'm saving the url for star trek as a string

star_trek_url <- "https://en.wikipedia.org/wiki/Star_Trek:_The_Next_Generation"

#Here's I'm gathering the tables from that site, I'm surprised there are 27
tables <- star_trek_url %>% 
  read_html() %>% 
  html_nodes("table")
```

```{r seasons}
#Here I'm just focusing on the second table. I have to "pluck" the second table from the list of tables. It took a guess or two to find it. 

Star_Trek_Air_Dates <- tables %>%
  purrr::pluck(2) %>%
  html_table() %>%
  clean_names() %>%                #Using clean names because an extra "season" column showed up
  select(-season,-episodes_2) %>%  #I'm getting rid of extra variables, they had the same name
  rename(                          #Just renaming columns
    Season = season_2,
    First_aired = originally_aired ,
    Last_aired = originally_aired_2
  )
  
Star_Trek_Air_Dates <- Star_Trek_Air_Dates[-1,]  #Getting rid of the first row

#I'm stuck on converting the dates. Maybe use seperate()?
#Note: Separate() is hard to do over "sep= (" so I had it figure it out automatically then used month_day_year

Star_Trek_Air_Dates <- Star_Trek_Air_Dates %>%
  separate(col = First_aired, into = c("a","b","c") ) %>%
  separate(col = Last_aired, into = c("e","f","g") ) %>%
  unite(col= "First_aired", a:c) %>%
  unite(col = "Last_aired", e:g)




Star_Trek_Air_Dates <- Star_Trek_Air_Dates %>%
  mutate(
    First_aired = as.Date(First_aired, "%B_%d_%Y"),
    Last_aired = as.Date(Last_aired, "%B_%d_%Y")
  )
Star_Trek_Air_Dates

#This is some lame graph, but I sure did learn lot about scraping and seperating. 
Star_Trek_Air_Dates %>%
  ggplot(mapping=aes(First_aired,episodes))+
  geom_point() +
  theme_bw() +
  labs(title = "Star Trek New Gen", x="Air Date") 
  
```