---
title: "Problem_1"
author: "Schwab"
date: "2/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(babynames)
```

Problem 1 (Easy): Angelica Schuyler Church (1756–1814) was the daughter of New York Governer Philip Schuyler and sister of Elizabeth Schuyler Hamilton. Angelica, New York was named after her. Using the babynames package generate a plot of the reported proportion of babies born with the name Angelica over time and interpret the figure.

```{r Angelica-name-plot}
#This uses the filter verb, which the students need for most of the chapter 3 problems. 

babynames %>%
  filter(name == "Angelica") %>% #Filter for only the names Angelica
  ggplot( aes(year,prop))+
  geom_point()          #I think this is the plot that the question is asking for. 
```



```{r Angelica-baby-names-suming-gender}
#This chunk uses filter verbs that are not cover until chapter 4, but demonstrates how to combine male and female Angelica babies. 

Angelica <- babynames %>%
  filter(name == "Angelica") %>% #Filter for only the names Angelica
  group_by(year) %>%            #Group by year to combine both male and female births
  mutate(total_gender_prop = sum(prop))  #This should sum the proportion of male and female births
  

Angelica %>%
  ggplot(aes(year,total_gender_prop))+
  geom_point()      
```

