---
title: "Problem_10"
author: "Schwab"
date: "3/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(ggthemes)
library(stringr)
babynames_dist <- make_babynames_dist()
options(scipen=1000)
update_geom_defaults("bar",   list(fill = "yellow","blue"))
```

I'm not done with this problem and I'm stuck. How do I do this without the verbs? 

Problem 10 (Hard): Use the  function in the mdsr package to recreate the “Deadest Names” graphic from FiveThirtyEight (https://fivethirtyeight.com/features/how-to-tell-someones-age-when-all-you-know-is-her-name).

```{r}
glimpse(babynames_dist)
```

```{r}
babynames_dist %>%
  filter(name=="Sam")
```

```{r}
babynames_dist %>%
  mutate(est_dead=n-est_alive_today) %>%
  #filter(sex=="M") %>%
  group_by(name) %>%
  summarise(percent_dead=100*sum(est_dead)/sum(n)) %>%
  filter(name=="Sam")
  
```

```{r}
babynames_dist %>%
  group_by(sex,name) %>%
  summarise(sum(n),dead=sum(n)-sum((trunc(est_alive_today))),percent_dead=dead/sum(n)) %>%
  filter(name=="Mabel")
```

Trying to filter by popular names

```{r}

head(babynames_dist)

dead_fem_names <- babynames_dist %>%
  group_by(name) %>%
  mutate(largest_prop=sum(prop),most_total_births=sum(n), dead = n-trunc(est_alive_today)) %>%
  filter(  sex == "F" ) %>% 
  group_by(name) %>%
  summarise(largest_prop, most_total_births,percent_dead = 100*(sum(dead)/sum(n)),sex )%>%
  #distinct() %>%
  #filter(name %in%  list("Mabel","Gertrude","Myrtle","Blanche","Beulah","Bessie","Pearl","Ethel","Minnie","Viola")) %>%
  arrange(desc(percent_dead)) %>%
  top_n(largest_prop,n=10) 
  


dead_male_names <- babynames_dist %>%
  filter( sex == "M" ) %>% 
  mutate(dead = n-trunc(est_alive_today)) %>%
  group_by(name) %>%
  summarise(percent_dead = 100*(sum(dead)/sum(n)) )%>%
  
  arrange(desc(percent_dead)) %>%
  slice_max(percent_dead,n=10,with_ties=FALSE) %>%
  mutate(sex="M")

dead_fem_names
dead_male_names
```

```{r}
#I choose the names for female here

list_of_fem_names <- list("Mabel","Gertrude","Myrtle","Blanche","Beulah","Bessie","Pearl","Ethel","Minnie","Viola")

dead_fem_names <- babynames_dist %>%
  filter(name %in% list_of_fem_names, sex == "F" ) %>% #This filters by the names in the list_of_fem_names
  mutate(dead = n-trunc(est_alive_today)) %>%   #This is a dead variable the number of people born minus those that are alive today. 
  group_by(name) %>%
  summarise(percent_dead = 100*(sum(dead)/sum(n)) )%>%  #I made a variable that shows the percent of people who died
  arrange(desc(percent_dead)) %>%
  mutate(sex="F") #Add the sex variable 

# I repeated the process for males as females. 
list_of_male_names <- list("Elmer","Clarence","Harry","Chester","Willard","Herman","Herbert","Claude","Fred","Sam")

dead_male_names <- babynames_dist %>%
  filter(name %in% list_of_male_names, sex == "M" ) %>% 
  mutate(dead = n-trunc(est_alive_today)) %>%
  group_by(name) %>%
  summarise(percent_dead = 100*(sum(dead)/sum(n)) )%>%
  arrange(desc(percent_dead)) %>%
  mutate(sex="M")


twenty_dead_names <- dead_fem_names %>% 
  full_join( dead_male_names) #I joined the two tables here and call is twenty dead names. 


twenty_dead_names %>%
  ggplot(aes(x= reorder(name,+percent_dead),y=percent_dead,fill=sex))+  #reorder puts higher percent at top
  geom_bar(stat= "identity",show.legend = FALSE ) + #turns of legend
  labs(title="Deadest Names", subtitle = str_wrap("Estimated percentage of Americans with a given name born since 1900 who were dead as of Jan 1, 2010" ,65))+ #str_wrap() wraps the subtitle
  coord_flip(ylim=c(30,80)) + # Just makes the graph horizontal and limits the y-values
  
  geom_text(aes(label=trunc(percent_dead)),hjust=-0.5)+ #This adds the numbers at the end of the bars
  theme_fivethirtyeight()+ # This starts the 538 theme and font 
  theme(axis.line=element_blank(),panel.background=element_blank(),axis.ticks = element_blank(),panel.grid.major =element_blank(), axis.text.x =  element_blank())+ #this turns off all extra numbers and axes
  scale_fill_manual("legend", values = c("F" = "#e5ae38", "M" = "#30a2da"))  #This sets the colors for male and female based on 538 color theme I found here https://www.color-hex.com/color-palette/13650
 
  
```




