---
title: "How R builds a graph"
author: "Schwab"
format: revealjs
editor: visual
---

```{r}
library(tidyverse)
#heights from sds 192.02.02 and 220
heights <- c(60,63,65,69,65,66,59,62,67,69,66,67,64,62,67,67,62,64,66,62,68,63,65,60,66,63,67,64.17,67.75,70,62.64,61,64.5,68,66,64,68,62,66,60,63,64,63,62.5,64,68,68,64,65,66,71,60.6,63,69,66,65,61,61,62,64,65.5,61,62,65,62,66,65,64,63,67,67,63,64.56)
heights <- as.data.frame(heights)
```

## Heights

```{r heights}

ggplot(data=heights,aes(x=heights)) +
  geom_histogram()+
  xlab("Heights (inches)")+
  ylab("Number of students")+
  labs(title = "The heights of Fall 2023 SDS students taught by Schwab")
  
```

## Code

```{r  echo=TRUE}

ggplot(data=heights,aes(x=heights)) +
  geom_histogram()+
  xlab("Heights (inches)")+
  ylab("Number of students")+
  labs(title = "The heights of Fall 2023 SDS students taught by Schwab")
  
```

## Be a computer

-   Revisit the old graphs that some responsible person held onto and choose your favorite as a group.

-   As a group come up with the code that could reproduce that graph. Write it on the same paper and upload a photo to slack channel #classwork.

-   We'll discuss as a class
