---
title: "How R builds a graph"
author: "Schwab"
format: 
  revealjs:
    theme: beige
editor: visual
---

```{r}
#| message: false

library(tidyverse)
#heights from sds 192.02.02 and 220
heights <- c(60,63,65,69,65,66,59,62,67,69,66,67,64,62,67,67,62,64,66,62,68,63,65,60,66,63,67,64.17,67.75,70,62.64,61,64.5,68,66,64,68,62,66,60,63,64,63,62.5,64,68,68,64,65,66,71,60.6,63,69,66,65,61,61,62,64,65.5,61,62,65,62,66,65,64,63,67,67,63,64.56)
heights <- as.data.frame(heights)
```

## Heights

```{r heights}

ggplot( data=heights , aes(x=heights) ) +
  geom_histogram() +
  xlab("Heights (inches)") +
  ylab("Number of students") +
  labs(title = "Heights" , 
       subtitle= "Schwab",
       caption = "The heights of Fall 2023 SDS 192.03 students as collected via google form", 
       ) 

  
```

## Code

```{r  echo=TRUE}

ggplot( data=heights , aes(x=heights) ) +
  geom_histogram() +
  xlab("Heights (inches)") +
  ylab("Number of students") +
  labs(title = "Heights" , 
       subtitle= "Schwab",
       caption = "The heights of Fall 2023 SDS 192.03 students as collected via google form", 
       ) 
  
```
