---
title: "maps-ggplot"
author: "Schwab"
format: revealjs
editor: visual
---

```{r setup}
library(tidyverse)
library(leaflet)
library(tidygeocoder)
library(maps)

CholeraDeaths_Book <-mdsr::CholeraDeaths
st_crs(CholeraDeaths_Book) = st_crs(CholeraDeaths_Book) 
```

<!-- Let's find the latitude and longitude for a couple of places. -->

```{r}

addresses<- tibble(address=c("50 Payson Ave, Easthampton, MA","Holyoke Community College, Holyoke,MA")) |>
geocode(address, method="osm") |>
  mutate(name = c("City Hall","HCC"))

addresses
```

<!-- Let's plot those with ggplot. -->

<!-- ```{r} -->
<!-- ggplot(addresses) + -->
<!--   geom_point(aes(long,lat))  -->
<!--   #coord_quickmap() -->


<!-- ``` -->

<!-- Not very exciting. We'll add it it in a moment. -->

<!-- Let's build a map of Massachusetts with the map_data() function -->

<!-- ```{r} -->
<!-- ma_counties <- map_data("county", "massachusetts") %>%  -->
<!--   select( long, lat, group, id = subregion) -->

<!-- head(ma_counties) -->

<!-- ``` -->

<!-- Notice there are a lot of points for barnstable. Those are the vertices of a polygon. Let's draw the polygon with the points. -->

<!-- ```{r} -->
<!-- ma_counties |> ggplot(aes(long,lat,group=group))+ -->
<!--   geom_polygon(fill = "white", colour = "grey50")+ -->
<!--   geom_point()+ -->
<!--   coord_quickmap() -->
<!-- ``` -->

<!-- Let's grab just Massachusetts cities from the data frame us.cities. -->

<!-- ```{r} -->
<!-- ma_cities <- us.cities %>%  -->
<!--   filter(country.etc =="MA") |> -->
<!--   select(name, long, lat) -->

<!-- head(ma_cities) -->
<!-- ``` -->

<!-- Exercise: Plot MA cities onto our county map. -->

<!-- ```{r} -->
<!-- ma_counties |> ggplot(aes(long,lat))+ -->
<!--   geom_polygon(fill = "white", colour = "grey50",aes(group=group)) + -->
<!--   #geom_point(data=ma_cities,.......) -->

<!--   coord_quickmap() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- class(ma_counties) -->
<!-- class(ma_cities) -->
<!-- ``` -->

<!-- Let's get some more accurate government data. -->

<!-- [Go here](https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html) and download some shape files. -->

<!-- Saving them will be a bit of work. First we need to find those files. -->

<!-- ```{r} -->
<!-- states <- read_sf("~/Documents/MTH_190_Intro_to_DS/course-materials/cb_2021_us_state_500k") |> -->
<!--   sf::st_transform('+proj=longlat +datum=WGS84') -->

<!-- counties <- read_sf("~/Documents/MTH_190_Intro_to_DS/course-materials/cb_2021_us_county_5m") |> -->
<!--   st_transform('+proj=longlat +datum=WGS84') -->
<!-- ``` -->

# Leaflet

Leaflet is a package for interactive maps. Note: leftlet is not ggplot() add functions with the `|>`

```{r}
mass_pop_orig <- 
  tidycensus::get_acs(
    geography = "county", 
    variables = "B01003_001", 
    state = "MA",
    geometry = TRUE
  ) 

leaflet() |>
  addTiles() 
```

# Polygons

```{r}
mass_pop_orig <- 
  tidycensus::get_acs(
    geography = "county", 
    variables = "B01003_001", 
    state = "MA",
    geometry = TRUE
  ) 

leaflet(mass_pop_orig) |>
  addTiles() |>
  addPolygons()
```

# Little markers

```{r}

leaflet() |>
  addTiles() |>
  addPolygons(data = mass_pop_orig) |>
  addMarkers(data = addresses, lng=~long, lat=~lat, popup = ~name)
  
```

# Adding Circle Markers

```{r}
ma_cities <- map.cities(country = "USA")

leaflet() |>
  addTiles() |>
  addPolygons(data = mass_pop_orig) |>
  addMarkers(data = addresses, lng=~long, lat=~lat, popup = ~name, ) |>
  addCircleMarkers(data = ma_cities, lng=~long, lat=~lat, popup = ~name, color='black',clusterOptions = markerClusterOptions() ) 
  
```

# 

```{r}
"new england city and town area"

leaflet() |>
  addTiles(urlTemplate = "Stadia.StamenWatercolor") |>
  addPolygons(data = Just_MA_counties) |>
  addMarkers(data = addresses, lng=~long, lat=~lat, popup = ~name, ) |>
  addCircleMarkers(data = ma_cities, lng=~long, lat=~lat, popup = ~name, color='black',clusterOptions = markerClusterOptions() ) 
```


